apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: page-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dguerrero11/page-public-demo"
    targetRevision: main
    path: k8s                # ArgoCD monitorea solo esta carpeta
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true       # borra recursos que ya no están en Git
      selfHeal: true    # restaura recursos borrados manualmente
    syncOptions:
      - CreateNamespace=true
